/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jarelio Filho
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        painellogin = new javax.swing.JPanel();
        userlabel = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        userlogin = new javax.swing.JTextField();
        passlogin = new javax.swing.JPasswordField();
        acesslogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(7, 9, 17));
        setResizable(false);

        painellogin.setBackground(new java.awt.Color(37, 39, 47));
        painellogin.setForeground(new java.awt.Color(255, 153, 153));

        userlabel.setBackground(new java.awt.Color(7, 9, 17));
        userlabel.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        userlabel.setForeground(new java.awt.Color(255, 153, 153));
        userlabel.setText("Usuário:");

        passlabel.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        passlabel.setForeground(new java.awt.Color(255, 153, 153));
        passlabel.setText("Senha:");

        userlogin.setBackground(new java.awt.Color(255, 204, 204));
        userlogin.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        userlogin.setToolTipText("");
        userlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userloginActionPerformed(evt);
            }
        });

        passlogin.setBackground(new java.awt.Color(255, 204, 204));
        passlogin.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        passlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passloginActionPerformed(evt);
            }
        });
        passlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passloginKeyPressed(evt);
            }
        });

        acesslogin.setBackground(new java.awt.Color(7, 9, 17));
        acesslogin.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        acesslogin.setForeground(new java.awt.Color(255, 153, 153));
        acesslogin.setText("Acessar");
        acesslogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelloginLayout = new javax.swing.GroupLayout(painellogin);
        painellogin.setLayout(painelloginLayout);
        painelloginLayout.setHorizontalGroup(
            painelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelloginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(painelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acesslogin)
                    .addGroup(painelloginLayout.createSequentialGroup()
                        .addComponent(passlabel)
                        .addGap(18, 18, 18)
                        .addComponent(passlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelloginLayout.createSequentialGroup()
                        .addComponent(userlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        painelloginLayout.setVerticalGroup(
            painelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelloginLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(painelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel))
                .addGap(28, 28, 28)
                .addGroup(painelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passlabel))
                .addGap(27, 27, 27)
                .addComponent(acesslogin)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painellogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void acessloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessloginActionPerformed
        if(this.checkLogin(userlogin.getText(), new String(passlogin.getPassword()))){
            JOptionPane.showMessageDialog(null,"Logado com sucesso!");
            new TelaPrincipal(userlogin.getText()).setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Usuário ou senha incorreta!");
        }
    }//GEN-LAST:event_acessloginActionPerformed
    
    private boolean checkLogin(String login, String senha){
        return login.equals("Jarelio")&&senha.equals("123456");     
    }
    
    private void passloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passloginKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(this.checkLogin(userlogin.getText(), new String(passlogin.getPassword()))){
                JOptionPane.showMessageDialog(null,"Logado com sucesso!");
                new TelaPrincipal(userlogin.getText()).setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null,"Usuário ou senha incorreta!");
            }
        }
    }//GEN-LAST:event_passloginKeyPressed

    private void passloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passloginActionPerformed

    private void userloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userloginActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acesslogin;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel painellogin;
    private javax.swing.JLabel passlabel;
    private javax.swing.JPasswordField passlogin;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField userlogin;
    // End of variables declaration//GEN-END:variables
}
