/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FaixaController;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.bean.Faixa;

/**
 *
 * @author Jarelio Filho
 */
public class TelaListarFaixasAlbum extends javax.swing.JDialog {

    private int cod_album;

    /**
     * Creates new form TelaListarFaixasAlbum
     */
    public TelaListarFaixasAlbum(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Faixa.setDefaultEditor(Object.class, null);
        this.listFaixas();
    }
    public TelaListarFaixasAlbum(java.awt.Dialog parent, boolean modal, int cod_album) {
        super(parent, modal);
        initComponents();
        Faixa.setDefaultEditor(Object.class, null);
        this.cod_album = cod_album;
        this.listFaixas();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addPlay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Faixa = new javax.swing.JTable();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Faixas do Album");
        setBackground(new java.awt.Color(7, 9, 17));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(37, 39, 47));

        addPlay.setBackground(new java.awt.Color(7, 9, 17));
        addPlay.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        addPlay.setForeground(new java.awt.Color(255, 153, 153));
        addPlay.setText("Adicionar em Playlist");
        addPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayActionPerformed(evt);
            }
        });

        Faixa.setBackground(new java.awt.Color(0, 102, 102));
        Faixa.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Faixa.setForeground(new java.awt.Color(255, 153, 153));
        Faixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Faixa", "Nome", "Duração"
            }
        ));
        Faixa.setFillsViewportHeight(true);
        Faixa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Faixa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Faixa);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color (47, 49, 57));

        for (int i = 0; i < Faixa.getModel().getColumnCount(); i++) {
            Faixa.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        voltar.setBackground(new java.awt.Color(7, 9, 17));
        voltar.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 153, 153));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlay)
                    .addComponent(voltar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void addPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayActionPerformed
        if(Faixa.getSelectedRow()!=-1){
            int cod_faixa = (int) Faixa.getValueAt(Faixa.getSelectedRow(),0);
            JDialog listarPlaylists = new TelaListarPlaylists(this, true, cod_faixa,cod_album, 0);
            listarPlaylists.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma faixa para Inserir");
        }

    }//GEN-LAST:event_addPlayActionPerformed
    private void listFaixas(){
        FaixaController faixac = new FaixaController();
        
        DefaultTableModel modelo = (DefaultTableModel) Faixa.getModel();
        modelo.setNumRows(0);
                
        for(Faixa f : faixac.selectFaixasAlbum(cod_album)){
            modelo.addRow(new Object[]{
                f.getNumFaixa(),
                f.getDescricao(),
                f.getTempoExec()
            });
        }        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarFaixasAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarFaixasAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarFaixasAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarFaixasAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaListarFaixasAlbum dialog = new TelaListarFaixasAlbum(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Faixa;
    private javax.swing.JButton addPlay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
