/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PlaylistController;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.bean.Playlist;

/**
 *
 * @author Jarelio Filho
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        Playlist.setDefaultEditor(Object.class, null);
        this.listPlaylist();
    }
    public TelaPrincipal(String nome) {
        initComponents();
        usuario.setText(nome);
        Playlist.setDefaultEditor(Object.class, null);
        this.listPlaylist();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        buscarMusic = new javax.swing.JButton();
        criarPlay = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Playlist = new javax.swing.JTable();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotper");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(37, 39, 47));

        buscarMusic.setBackground(new java.awt.Color(7, 9, 17));
        buscarMusic.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        buscarMusic.setForeground(new java.awt.Color(255, 153, 153));
        buscarMusic.setText("Buscar Músicas");
        buscarMusic.setBorderPainted(false);
        buscarMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMusicActionPerformed(evt);
            }
        });

        criarPlay.setBackground(new java.awt.Color(7, 9, 17));
        criarPlay.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        criarPlay.setForeground(new java.awt.Color(255, 153, 153));
        criarPlay.setText("Criar Playlist");
        criarPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPlayActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(7, 9, 17));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Ver Playlist");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(7, 9, 17));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Apagar Playlist");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        usuario.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 153, 153));
        usuario.setText("Usuário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(buscarMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(criarPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(37, 39, 47));

        Playlist.setBackground(new java.awt.Color(0, 102, 102));
        Playlist.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Playlist.setForeground(new java.awt.Color(255, 153, 153));
        Playlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Playlist", "Nome Playlist", "Data Criação", "Duração"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Playlist.setFillsViewportHeight(true);
        Playlist.setGridColor(new java.awt.Color(7, 9, 17));
        Playlist.setSelectionBackground(new java.awt.Color(0, 0, 255));
        Playlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Playlist.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Playlist);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color (47, 49, 57));

        for (int i = 0; i < Playlist.getModel().getColumnCount(); i++) {
            Playlist.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.listPlaylist();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Playlist.getSelectedRow()!=-1){
            int cod_play = (int) Playlist.getValueAt(Playlist.getSelectedRow(),0);
            PlaylistController playc = new PlaylistController();
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente remover essa playlist?","Confirmar remoção",YES_NO_OPTION);
            if(resposta == JOptionPane.YES_OPTION){
                if(playc.deletePlaylist(cod_play)){
                    JOptionPane.showMessageDialog(null, "Playlist removida com sucesso!");
                    this.listPlaylist();
                }else{
                    JOptionPane.showMessageDialog(null, "Falha ao remover playlist!");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Selecione uma playlist!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Playlist.getSelectedRow()!=-1){
            int cod_play = (int) Playlist.getValueAt(Playlist.getSelectedRow(),0);
            JDialog telaListarFaixasPlaylist = new TelaListarFaixasPlaylist(this,true,cod_play);
            telaListarFaixasPlaylist.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Selecione uma playlist!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void criarPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPlayActionPerformed
        JDialog criarPlaylist = new TelaCriarPlaylist(this, true);
        criarPlaylist.setVisible(true);
        this.listPlaylist();
    }//GEN-LAST:event_criarPlayActionPerformed

    private void buscarMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMusicActionPerformed
        JDialog listarAlbuns = new TelaListarAlbuns(this, true);
        listarAlbuns.setVisible(true);
    }//GEN-LAST:event_buscarMusicActionPerformed
    
    private void listPlaylist(){
        PlaylistController playc = new PlaylistController();
        
        DefaultTableModel modelo = (DefaultTableModel) Playlist.getModel();
        modelo.setNumRows(0);
                
        for(Playlist p : playc.getPlaylists()){
            modelo.addRow(new Object[]{
                p.getCodPlay(),
                p.getNome(),
                p.getDataCriacao(),
                p.getDuracaoExec()
            });
        }
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Playlist;
    private javax.swing.JButton buscarMusic;
    private javax.swing.JButton criarPlay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
