/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlbumController;
import controller.FaixaController;
import controller.PlaylistController;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.bean.Faixa;

/**
 *
 * @author Jarelio Filho
 */
public class TelaListarFaixasPlaylist extends javax.swing.JDialog {

    private int cod_play;

    /**
     * Creates new form TelaListarFaixasPlaylist
     */
    public TelaListarFaixasPlaylist(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Faixas.setDefaultEditor(Object.class, null);
        
        ((DefaultTableCellRenderer) Faixas.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        Faixas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        
        this.listFaixas();
    }
    
    public TelaListarFaixasPlaylist(java.awt.Frame parent, boolean modal, int cod_play) {
        super(parent, modal);
        this.cod_play = cod_play;
        initComponents();
        Faixas.setDefaultEditor(Object.class, null);
        
        ((DefaultTableCellRenderer) Faixas.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        Faixas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        
        this.listFaixas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Faixas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Faixas da Playlist");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(37, 39, 47));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        jButton1.setBackground(new java.awt.Color(7, 9, 17));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Remover da Playlist");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Faixas.setBackground(new java.awt.Color(0, 102, 102));
        Faixas.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Faixas.setForeground(new java.awt.Color(255, 153, 153));
        Faixas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Album", "Faixa", "Duração"
            }
        ));
        Faixas.setFillsViewportHeight(true);
        Faixas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Faixas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Faixas);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color (47, 49, 57));

        for (int i = 0; i < Faixas.getModel().getColumnCount(); i++) {
            Faixas.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        jButton2.setBackground(new java.awt.Color(7, 9, 17));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listFaixas(){
        FaixaController faixac = new FaixaController();
        AlbumController albc = new AlbumController();
        
        DefaultTableModel modelo = (DefaultTableModel) Faixas.getModel();
        modelo.setNumRows(0);
                
        for(Faixa f : faixac.selectFaixasPlaylist(cod_play)){
            modelo.addRow(new Object[]{
                albc.getAlbumFaixa(f.getCodAlbum()).getDescricao(),
                f.getDescricao(),
                f.getTempoExec()
            });
        }        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Faixas.getSelectedRow()!=-1){
            String descricao = (String) Faixas.getValueAt(Faixas.getSelectedRow(),1);
            FaixaController faixac = new FaixaController();
            PlaylistController playc = new PlaylistController();
            Faixa faixa = faixac.selectFaixaDescricao(descricao);
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente remover essa faixa?","Confirmar remoção",YES_NO_OPTION);
            if(resposta == JOptionPane.YES_OPTION){
                if(faixac.deleteFaixaPlaylist(faixa.getNumFaixa(),faixa.getCodAlbum(),playc.selectPlaylistFaixa(descricao))){
                    JOptionPane.showMessageDialog(null, "Faixa removida com sucesso da Playlist!");
                    this.listFaixas();
                }else{
                    JOptionPane.showMessageDialog(null, "Falha ao remover faixa da Playlist!");
                }
            }
        }else{
           JOptionPane.showMessageDialog(null,"Selecione uma faixa para remover!"); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarFaixasPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarFaixasPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarFaixasPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarFaixasPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaListarFaixasPlaylist dialog = new TelaListarFaixasPlaylist(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Faixas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
